### ISSUE TITLE
能解析一下upload组件么?

### ISSUE THREAD

**Issue by bihell** [b-zai/vben-learn#1]
upload组件我用的很迷茫,不知道你这边有计划解析解析么?  搞个例子之类

**Comment by b-zai** [comment]
可以看antd vue和vben的文档示例，写的挺详细了。
antd vue: https://2x.antdv.com/components/upload-cn
vben: https://vvbin.cn/doc-next/components/upload.html

**Comment by bihell** [comment]
哦没事啦,我已经搞定啦. @b-zai
